version: '3'

services:
    db:
        image: mysql:8.0
        restart: always
        container_name: db
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        volumes:
            - ./mysql-test:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        restart: always
        environment:
          PMA_HOST: db
        depends_on:
            - db


